author           = InnovAnon
depends          = default, drinks, placeable_buckets
description      = Liquid counterpart to pooper / Nature's Call
name             = peeer
optional_depends = pedology
title            = IA Peeer

